In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("E:/datafiles/Home_Price.csv")
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.Bedrooms.median()

3.5

In [4]:
import math
median_Bedrooms = math.floor(df.Bedrooms.median())
median_Bedrooms

3

In [5]:
df.Bedrooms.fillna(median_Bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: Bedrooms, dtype: float64

In [7]:
df.Bedrooms = df.Bedrooms.fillna(median_Bedrooms)
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['Area','Bedrooms','Age']],df.Price)

LinearRegression()

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383725.00000000006

In [12]:
reg.predict([[3000,3,40]])

array([444400.])

In [13]:
#y = m1*x1 + m2*x2 + m3*x3 + b
#Price = m1*Area + m2*Bedrooms + m3*Age + b
137.25*3000+-26025*3+-6825*40+383725.00000000006


444400.00000000006

In [14]:
reg.predict([[2500,4,5]])

array([588625.])

In [15]:
#y = m1*x1 + m2*x2 + m3*x3 + b
#Price = m1*Area + m2*Bedrooms + m3*Age + b
137.25*2500+-26025*4+-6825*5+383725.00000000006


588625.0