In [1]:
#Word Emdedding Techniques Using Embedding Layer in Keras
#Libraries used Tensorflow <2.0 and Keras
#Libraries used Tensorflow > 2.0 and Keras

#from keras.preprocessing.text import one_hot  Tensorflow<2.0

from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size from the dictionary of words created

voc_size=10000

In [5]:
#One Hot Representation

#Which is used to create an index from the dictionary of words for each unique word

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6925, 8564, 5168, 3650], [6925, 8564, 5168, 1144], [6925, 2003, 5168, 424], [5384, 3192, 7137, 3867, 7533], [5384, 3192, 7137, 3867, 1376], [2566, 6925, 4806, 5168, 5691], [1580, 1374, 2818, 3867]]


In [6]:
#Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
#The index obtained from one hot encoding of words to embedded layer keras to form embedding matrix
#We are taking sent_length=8, by default and adding additional zeros with padding(pre(starting)) for equal sentance flow

sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6925 8564 5168 3650]
 [   0    0    0    0 6925 8564 5168 1144]
 [   0    0    0    0 6925 2003 5168  424]
 [   0    0    0 5384 3192 7137 3867 7533]
 [   0    0    0 5384 3192 7137 3867 1376]
 [   0    0    0 2566 6925 4806 5168 5691]
 [   0    0    0    0 1580 1374 2818 3867]]


In [9]:
#dimension of the features representation

dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-2.04347614e-02 -4.79699038e-02 -3.69624607e-02 -1.94980986e-02
   -1.78568251e-02  1.95142739e-02 -5.27725369e-03  1.33774541e-02
    1.00025311e-02 -1.35333464e-03]
  [-2.04347614e-02 -4.79699038e-02 -3.69624607e-02 -1.94980986e-02
   -1.78568251e-02  1.95142739e-02 -5.27725369e-03  1.33774541e-02
    1.00025311e-02 -1.35333464e-03]
  [-2.04347614e-02 -4.79699038e-02 -3.69624607e-02 -1.94980986e-02
   -1.78568251e-02  1.95142739e-02 -5.27725369e-03  1.33774541e-02
    1.00025311e-02 -1.35333464e-03]
  [-2.04347614e-02 -4.79699038e-02 -3.69624607e-02 -1.94980986e-02
   -1.78568251e-02  1.95142739e-02 -5.27725369e-03  1.33774541e-02
    1.00025311e-02 -1.35333464e-03]
  [ 1.80482529e-02  2.68484391e-02  2.20237859e-02 -4.10939567e-02
    1.68400668e-02 -3.52526531e-02  1.13908276e-02  3.18313949e-02
   -3.11947111e-02 -1.96832549e-02]
  [-4.30446863e-03 -2.42562424e-02 -3.73121984e-02  4.04275581e-03
    2.58445032e-02 -1.44618861e-02 -3.37616690e-02 -1.74679048e-02
    1.83882155e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6925, 8564, 5168, 3650])

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.02043476 -0.0479699  -0.03696246 -0.0194981  -0.01785683  0.01951427
  -0.00527725  0.01337745  0.01000253 -0.00135333]
 [-0.02043476 -0.0479699  -0.03696246 -0.0194981  -0.01785683  0.01951427
  -0.00527725  0.01337745  0.01000253 -0.00135333]
 [-0.02043476 -0.0479699  -0.03696246 -0.0194981  -0.01785683  0.01951427
  -0.00527725  0.01337745  0.01000253 -0.00135333]
 [-0.02043476 -0.0479699  -0.03696246 -0.0194981  -0.01785683  0.01951427
  -0.00527725  0.01337745  0.01000253 -0.00135333]
 [ 0.01804825  0.02684844  0.02202379 -0.04109396  0.01684007 -0.03525265
   0.01139083  0.03183139 -0.03119471 -0.01968325]
 [-0.00430447 -0.02425624 -0.0373122   0.00404276  0.0258445  -0.01446189
  -0.03376167 -0.0174679   0.01838822  0.01328199]
 [-0.00503886  0.01150563 -0.04166489  0.00496687 -0.00791984  0.02368564
   0.02970295 -0.01437042  0.00460567 -0.00228516]
 [-0.00411842 -0.02964795 -0.04119142  0.00154641 -0.03325708  0.03503969
  -0.01545881  0.02493683  0.04973575 -0.02433583]]