# Data Analysis with Numpy

In [1]:
# *****1.Creating a NumPy Array****
# Basic ndarray

import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
#To get the basic information from the created array using np.array

a = np.array([1,2,3,4,5])
a # [1 2 3 4 5]

array([1, 2, 3, 4, 5])

In [3]:
#To get the shape of the array

a.shape # shape of the array: (5,)

(5,)

In [4]:
#To get the datatype of the array

a.dtype # type of the elements: int32

dtype('int32')

In [5]:
#To get the number of dimensions of the array

a.ndim # number of dimensions: 1

1

In [6]:
#To get the size/total number of elements in the array

a.size # total number of elements: 5

5

In [7]:
#To get the size in bytes of each element in the array

a.itemsize # the size in bytes of each element: 4

4

In [8]:
#Creating Multidimentional arrays in numpy

#creating 2-D array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#Creating 3-D array

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#Creating 4-D array

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
#Array of zeros
#All you have to do is pass the shape of the desired array<here shape = 5>:
#This is 1-D array

a = np.zeros(3)
print(a)

[0. 0. 0.]


In [12]:
#This is 2-D array here 2 = rows(denoted by n) and 3 = columns(denoted by m)

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#This is 3-D array here 3 = rows(denoted by n) and 3 = columns(denoted by m)

a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#Array of ones

#This is 1-D array
a = np.ones(3,dtype = np.int32)
print(a)

[1 1 1]


In [15]:
#This is 2-D array here 2 = rows(denoted by n) and 3 = columns(denoted by m)

a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#This is 3-D array here 3 = rows(denoted by n) and 3 = columns(denoted by m)

a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#Random numbers in ndarrays
# Random Decimal values
#It creates an array of a given shape with random values from [0,1):

#This is 1-D array
a = np.random.rand(3)
print(a)

[0.72599072 0.49436282 0.48596828]


In [18]:
#This is 2-D array

a = np.random.rand(2,3)
print(a)

[[0.50602482 0.81188432 0.38819712]
 [0.00944638 0.90347352 0.28031565]]


In [19]:
#This is 3-D array

a = np.random.rand(3,3)
print(a)

[[0.95105481 0.54083509 0.11660774]
 [0.23688788 0.69632329 0.69696663]
 [0.85164942 0.78684535 0.47719465]]


In [20]:
# Random Integer values
a = np.random.randint(-4,8, size=(3,3))
print(a)

[[ 2  6  7]
 [ 1 -4 -3]
 [ 6  5  3]]


In [21]:
# An array of your choice

# Or, in fact, you can create an array filled with any given value using the np.full() method. 
# Just pass in the shape of the desired array and the value you want:

#1-D array
a = np.full((1,3),[[1,0,0]])
print(a)

[[1 0 0]]


In [22]:
#2-D array

a = np.full((2,3),[[1,0,0],[0,1,0]])
print(a)

[[1 0 0]
 [0 1 0]]


In [23]:
#3-D array

a = np.full((3,3),[[1,0,0],[0,1,0],[0,0,1]])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [24]:
# To fill a desired number completely in the array

a = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
b = np.full_like(a, 4)
print(b)

[[4 4 4 4 4]
 [4 4 4 4 4]]


In [25]:
# The identity matrix

a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# identity matrix
# Imatrix in NumPy
# Another great method is np.eye() that returns an array with 1s along its diagonal and 0s everywhere else.

a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# not an identity matrix
#k = 1 +ve value indicates upper side diagonal
a = np.eye(3,k=1)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [28]:
# not an identity matrix
#k = 1 -ve value indicates lower side diagonal

np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [29]:
# To Repeat an array

a = np.array([[1,2,3]])
r = np.repeat(a,3, axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
#Be carefull while copying the arrays from one variable to another variable.

#Copy Array using Numpy
#In the following example, we will copy the elements of an array a to another array b.

# create a numpy array
a = np.array([[8, 2, 3],
              [4, 7, 6]])

# copy contents of a to b
b = a.copy()

# modify a
a[1, 2] = 13

# check if b has remained the same
print('a\n',a)
print('\nb\n',b)

#Note:-Even if we have changed the contents of a,the contents of b are unaffected when using "b = a.copy()""

a
 [[ 8  2  3]
 [ 4  7 13]]

b
 [[8 2 3]
 [4 7 6]]


In [31]:
# What happens if we use assignment operator to copy array
# This is a negative scenario. This example explains why you should use copy() function instead of 
# assignment operator when you have to create a duplicate of an array.

# create a numpy array
a = np.array([[8, 2, 3],
              [4, 7, 6]])

# assign a to b
b = a

# modify a
a[1, 2] = 13

# check if b has remained the same
print('a\n',a)
print('\nb\n',b)

#Note:-b acts as a mere reference to a.And when you change a,then b also gets changed when using "b = a". 

# Hence, using assignment operator is not a way to duplicate or copy a numpy array.

a
 [[ 8  2  3]
 [ 4  7 13]]

b
 [[ 8  2  3]
 [ 4  7 13]]


In [32]:
#Evenly spaced ndarray by using np.arrange()

#The start,end and step size of the interval of values can be explicitly defined by passing in three 
#numbers as arguments for these values respectively. A point to be noted here is that the interval is 
#defined as [start,end) where the last number will not be included in the array:

#without passing the parameters
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [33]:
#passing the parameters[start,end,step_size]
a = np.arange(2,10,2)
print(a)

#Note:-Alternate elements were printed because the step-size was defined as 2. 
#Notice that 10 was not printed as it was the last element.

[2 4 6 8]


In [34]:
#Evenly spaced ndarray by using np.linspace()

# Here instead of step size,it takes in the number of samples that need to be retrieved from the interval.
# A point to note here is that the last number is included in the values returned unlike in the case of 
# np.arange().

a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [35]:
#*********2.The Shape and Reshaping of NumPy Array*********
# Once you have created your ndarray, the next thing you would want to do is check the number of axes, 
# shape, and the size of the ndarray

# 1.Dimensions of NumPy array
# 2.Shape of NumPy array
# 3.Size of NumPy array
# 4.Reshaping a NumPy array
# 5.Flattening a NumPy array
# 6.Transpose of a NumPy array

In [36]:
# 1.Dimensions of NumPy arrays
#We can get the ndimensional of the array 1-D,2-D,3-D.....

a = np.array([[5,10,15],[20,25,20]])
print('Array :','\n',a)
print('Dimensions :','\n',a.ndim)

Array : 
 [[ 5 10 15]
 [20 25 20]]
Dimensions : 
 2


In [37]:
# 2.Shape of NumPy array
#Here we can get the shape of the array,even deeper we get the individual rows and columns shapes values 

a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows =  2
Columns =  3


In [38]:
# 3.Size of NumPy array
# we can determine how many values there are in the array using the size attribute. 
# It just multiplies the number of rows(n) by the number of columns(m) in the ndarray:
#Here n=2 and m=3 (nxm=2x3=6),here shape =2-D N-dmin=2 array(2,3),size = 6

# size of array
a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Size of array : 6
Manual determination of size of array : 6


In [39]:
# 4.Reshaping a NumPy array
# Reshaping a ndarray can be done using the np.reshape() method. It changes the shape of the ndarray
# without changing the data within the ndarray:

# Here,we reshaped the ndarray from a 1-D to a 2-D ndarray.

a = np.array([3,6,9,12])
b = np.reshape(a,(2,2))
print(b)

[[ 3  6]
 [ 9 12]]


In [40]:
# While reshaping,if you are unsure about the shape of any of the axis, just input -1. NumPy automatically
# calculates the shape when it sees a -1:

a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


In [41]:
# 5.Flattening a NumPy array
# Sometimes when you have a multidimensional array and want to collapse it to a single-dimensional array, 
# you can either use the flatten() method or the ravel() method:

a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


In [42]:
# But an important difference between flatten() and ravel() is that the former returns a copy of the 
# original array while the latter returns a reference to the original array. This means any changes 
# made to the array returned from ravel() will also be reflected in the original array while this will 
# not be the case with flatten().

# Here flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray.

# Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by 
# flatten() is now pointing to this memory location.Therefore,any changes made here will not be reflected 
# in the original ndarray.

# Shallow copy, on the other hand, returns a reference to the original memory location.Meaning the object 
# returned by ravel() is pointing to the same memory location as the original ndarray object.So,definitely,
# any changes made to this ndarray will also be reflected in the original ndarray too.

a = np.ones((2,2))
b = a.flatten()
c = a.ravel()

In [43]:
#Flatten:- any changes made to the flatten array will not be reflected in the original array.

b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


In [44]:
#Ravel:- any changes made to the ravel array will be reflected in the original array.

c[0] = 0
print(a)

[[0. 1.]
 [1. 1.]]


In [45]:
# 6.Transpose of a NumPy array
# It takes the input array and swaps the rows with the column values,and the column values with the values
# of the rows:

a = np.array([[1,2,3],
[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


In [46]:
# *************3.Expanding and Squeezing a NumPy Array***************
# 1.Expanding a NumPy array
# 2.Squeezing a NumPy array

In [47]:
# Expanding a NumPy array
# You can add a new axis to an array using the expand_dims() method by providing the array and the axis 
# along which to expand:
# “axis 0” represents columns(horizontal) and “axis 1” represents rows(vertical)

a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)
print('Original:','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)
print('Expand along rows:','\n','Shape',c.shape,'\n',c)

Original: 
 Shape (3,) 
 [1 2 3]
Expand along columns: 
 Shape (1, 3) 
 [[1 2 3]]
Expand along rows: 
 Shape (3, 1) 
 [[1]
 [2]
 [3]]


In [48]:
# 2.Squeezing a NumPy array
# If we want to reduce the axis of the array, use the squeeze() method.It removes the axis that has a 
# single entry.This means if you have created a 2 x 2 x 1 matrix, squeeze() will remove the third 
# dimension from the matrix:

a = np.array([[[1,2,3],
[4,5,6]]])
b = np.squeeze(a, axis=0)
print('Original','\n','Shape',a.shape,'\n',a)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]
Squeeze array: 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]


In [49]:
a = np.array([[[[1,2,3],
[4,5,6]]]])
b = np.squeeze(a, axis=1)
print('Original','\n','Shape',a.shape,'\n',a)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (1, 1, 2, 3) 
 [[[[1 2 3]
   [4 5 6]]]]
Squeeze array: 
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]


In [50]:
a = np.array([[[[[1,2,3],
[4,5,6]]]]])
b = np.squeeze(a, axis=2)
print('Original','\n','Shape',a.shape,'\n',a)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

# Note:-However,if you already had a 2 x 2 matrix, using squeeze() in that case would give you an error:
# ValueError: cannot select an axis to squeeze out which has size not equal to one
# a = np.array([[[[[1,2,3],
# [4,5,6]]]]])
# b = np.squeeze(a, axis=3)
# print('Original','\n','Shape',a.shape,'\n',a)
# print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (1, 1, 1, 2, 3) 
 [[[[[1 2 3]
    [4 5 6]]]]]
Squeeze array: 
 Shape (1, 1, 2, 3) 
 [[[[1 2 3]
   [4 5 6]]]]


In [51]:
# ************5.Indexing and Slicing of NumPy Array**************
# 1.Slicing 1-D NumPy arrays
# 2.Slicing 2-D NumPy arrays
# 3.Slicing 3-D NumPy arrays
# 4.Negative slicing of NumPy arrays

# Index has two types:- 
# 1.Positive_Index starts from [ 0,1,2,3,4,5,6....+n ]
# 2.Negative_Index starts from [ -1,-2,-3,-4,-5,-6....-n ]

#Slicing have an inbuilt parameter exceution [[start_value:end_value:step_size]]
#start_value:- It is the positive value which starts with 0, we can give prefered positive value
#end_value:- It is the negative value which starts with -1, we can give prefered negative value
#step_size:- It is the increment size we can use in slicing an array starts from 1,...n(size of array).

In [52]:
# 1.Slicing 1-D NumPy arrays
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])

#last element did not get considered.because slicing includes the start index but excludes the end index.

[2 4]


In [53]:
a = np.array([1,2,3,4,5,6])
print(a[1:6:2])

#  This is the next higher index to the final index value you want to retrieve:

[2 4 6]


In [54]:
# If you don’t specify the start or end index,it is taken as 0 or array size,respectively, as default. 
# And the step-size by default is 1.

a = np.array([1,2,3,4,5,6])
print(a[:6:2])
print(a[1::2])
print(a[1:6:])
print(a[::])

[1 3 5]
[2 4 6]
[2 3 4 5 6]
[1 2 3 4 5 6]


In [55]:
# 2.Slicing 2-D NumPy arrays
# A 2-D array has rows and columns.

a = np.array([[1,2,3],
              [4,5,6]])
print(a[0,0]) #from 0-row=[1,2,3] 0-column[1] =====> then result is:1
print(a[1,2]) #from 1-row=[4,5,6] 2-column[6] =====> then result is:6
print(a[1,0]) #from 1-row=[4,5,6] 0-column[4] =====> then result is:4

1
6
4


In [56]:
a = np.array([[1,2,3],
              [4,5,6]])

#print the original array rows and columns
print('Original array :','\n',a)

# print first row values
print('First row values :','\n',a[0:1,:])

# print first row first value
print("First row First value:",'\n',a[0:1,0:1:])

# print first row second value
print("First row second value:",'\n',a[0:1,1:2:])

# print first row third value
print("First row third value:",'\n',a[0:1,2:3:])

# print second row values
print('second row values :','\n',a[1:2,:])

# print second row first value
print("Second row First value:",'\n',a[1:2,0:1:])

# print second row second value
print("Second row First value:",'\n',a[1:2,1:2:])

# print second row third value
print("Second row First value:",'\n',a[1:2,2:3:])

# with step-size for rows for first row alternate values
print('Alternate values from first row:','\n',a[0:1,::2])

# with step-size for rows for second row alternate values
print('Alternate values from second row:','\n',a[1:2,::2])

# print first column values
print('First column values :','\n',a[:,0:1:])

# print second column values
print('Second column values :','\n',a[:,1:2:])

# print third column values
print('Third column values :','\n',a[:,2:3:])

Original array : 
 [[1 2 3]
 [4 5 6]]
First row values : 
 [[1 2 3]]
First row First value: 
 [[1]]
First row second value: 
 [[2]]
First row third value: 
 [[3]]
second row values : 
 [[4 5 6]]
Second row First value: 
 [[4]]
Second row First value: 
 [[5]]
Second row First value: 
 [[6]]
Alternate values from first row: 
 [[1 3]]
Alternate values from second row: 
 [[4 6]]
First column values : 
 [[1]
 [4]]
Second column values : 
 [[2]
 [5]]
Third column values : 
 [[3]
 [6]]


In [57]:
# Slicing 3-D NumPy arrays

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

#print the original array rows and columns
print('Original array :','\n',a)

# print first row values
print('First row values :','\n',a[0:1,:])

# print first row first value
print("First row First value:",'\n',a[0:1,0:1:])

# print first row second value
print("First row Second value:",'\n',a[0:1,1:2:])

# print first row third value
print("First row Third value:",'\n',a[0:1,2:3:])

# print second row values
print('second row values :','\n',a[1:2,:])

# print second row first value
print("Second row First value:",'\n',a[1:2,0:1:])

# print second row second value
print("Second row Second value:",'\n',a[1:2,1:2:])

# print second row third value
print("Second row Third value:",'\n',a[1:2,2:3:])

# print third row values
print('Third row values :','\n',a[2:3,:])

# print third row first value
print("Third row First value:",'\n',a[2:3,0:1:])

# print third row second value
print("Third row Second value:",'\n',a[2:3,1:2:])

# print third row third value
print("Third row Third value:",'\n',a[2:3,2:3:])

# with step-size for rows for first row alternate values
print('Alternate values from first row:','\n',a[0:1,::2])

# with step-size for rows for second row alternate values
print('Alternate values from second row:','\n',a[1:2,::2])

# with step-size for rows for third row alternate values
print('Alternate values from second row:','\n',a[2:3,::2])

# print first column values
print('First column values :','\n',a[:,0:1:])

# print second column values
print('Second column values :','\n',a[:,1:2:])

# print third column values
print('Third column values :','\n',a[:,2:3:])

# with step-size for columns for first column alternate values
print('Alternate values from First column:','\n',a[:,0:1:2])

# with step-size for rows for second column alternate values
# print('Alternate values from Second column:','\n',a[:,1:2:2])

# with step-size for rows for third column alternate values
# print('Alternate values from Third column:','\n',a[:,2:3:2])

Original array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row values : 
 [[1 2 3]]
First row First value: 
 [[1]]
First row Second value: 
 [[2]]
First row Third value: 
 [[3]]
second row values : 
 [[4 5 6]]
Second row First value: 
 [[4]]
Second row Second value: 
 [[5]]
Second row Third value: 
 [[6]]
Third row values : 
 [[7 8 9]]
Third row First value: 
 [[7]]
Third row Second value: 
 [[8]]
Third row Third value: 
 [[9]]
Alternate values from first row: 
 [[1 3]]
Alternate values from second row: 
 [[4 6]]
Alternate values from second row: 
 [[7 9]]
First column values : 
 [[1]
 [4]
 [7]]
Second column values : 
 [[2]
 [5]
 [8]]
Third column values : 
 [[3]
 [6]
 [9]]
Alternate values from First column: 
 [[1]
 [4]
 [7]]


In [58]:
# 3-D array

x = np.arange(45).reshape(3,3,5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [59]:
# To get the first 2-D array

x[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
# To get the second 2-D array

x[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:
# To get the third 2-D array

x[2]

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [62]:
# To get the first row value in 1st 2-D array

x[0][0]

array([0, 1, 2, 3, 4])

In [63]:
# To get the first row value in 2nd 2-D array

x[1][0]

array([15, 16, 17, 18, 19])

In [64]:
# To get the first row value in 3rd 2-D array

x[2][0]

array([30, 31, 32, 33, 34])

In [65]:
# with step-size for rows for first row alternate values in 1st 2-D array

x[0][0:1,::2]

array([[0, 2, 4]])

In [66]:
# with step-size for rows for first row alternate values in 2nd 2-D array

x[1][0:1,::2]

array([[15, 17, 19]])

In [67]:
# with step-size for rows for first row alternate values in 3rd 2-D array

x[2][0:1,::2]

array([[30, 32, 34]])

In [68]:
# To get the all first row elements from 1st,2nd,3rd 2-D arrays

x[0:,0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34]])

In [69]:
# To get the all second row elements from 1st,2nd,3rd 2-D arrays

x[0:,1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [35, 36, 37, 38, 39]])

In [70]:
# To get the all third row elements from 1st,2nd,3rd 2-D arrays

x[0:,2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44]])

In [71]:
#To get all the 
x[0:,0:1,0:]

array([[[ 0,  1,  2,  3,  4]],

       [[15, 16, 17, 18, 19]],

       [[30, 31, 32, 33, 34]]])

In [72]:
x[0:,0:4,1]

array([[ 1,  6, 11],
       [16, 21, 26],
       [31, 36, 41]])

In [73]:
# Negative slicing of NumPy arrays
# Negative slicing prints elements from the end rather than the beginning. Have a look below:

a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print(a[:,-1])

[ 5 10]


In [74]:
print(a[:,-1:-3:-1])

[[ 5  4]
 [10  9]]


In [75]:
# An interesting use of negative slicing is to reverse the original array.

a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [76]:
# use the flip() method to reverse an ndarray.

a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [77]:
# ************6.Stacking and Concatenating NumPy arrays****************
# 1.Stacking ndarrays
# You can create a new array by combining existing arrays. This you can do in two ways:

#1.Either combine the arrays vertically (i.e. along the rows) using the vstack() method,thereby increasing
# the number of rows in the resulting array

#2.combine the arrays in a horizontal fashion(i.e. along the columns) using the hstack(),thereby increasing
# the number of columns in the resultant array

a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

# Note:-A point to note here is that the axis along which you are combining the array should have the same
# size otherwise you are bound to get an error!
# array_1 =[1,2,3,4,5],array_2 =[5,6,7,8] here array_1 ,size=5 and array_2 ,size=4 having different sizes.

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


In [78]:
#3.using the dstack() method combines array elements index by index and stacks them along the depth axis.

a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Dstack :','\n',c)
print(c.shape)

Array 1 : 
 [[1, 2], [3, 4]]
Array 2 : 
 [[5, 6], [7, 8]]
Dstack : 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [79]:
# Concatenating ndarrays

# While stacking arrays is one way of combining old arrays to get a new one,you could also use the 
# concatenate() method where the passed arrays are joined along an existing axis:

a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))

# Note:-The drawback of this method is that the original array must have the axis along which you want to
# combine. Otherwise, get ready to be greeted by an error.

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]


In [80]:
# append method that adds new elements to the end of a ndarray. This is obviously useful when you already 
# have an existing ndarray but want to add new values to it.

# append values to ndarray

a = np.array([[1,2],
             [3,4]])
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
# ***************7.Broadcasting in NumPy arrays – A class apart!*************

# Broadcasting is one of the best features of ndarrays.It lets you perform arithmetics operations between 
# ndarrays of different sizes or between an ndarray and a simple number!

# Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger 
# ndarray, by using this we can reduce the number of spaces occupied by each bit in the memory allocation.

a = np.arange(10,20,2)
b = np.array([[2],[2]])
print('Adding two different size arrays :','\n',a+b)
print('Multiplying an ndarray and a number :',a*2)

Adding two different size arrays : 
 [[12 14 16 18 20]
 [12 14 16 18 20]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [82]:
# Its working can be thought of like stretching or making copies of the scalar, the number, [2, 2, 2] to 
# match the shape of the ndarray and then perform the operation element-wise.But no such copies are being 
# made.It is just a way of thinking about how broadcasting is working.

# This is very useful because it is more efficient to multiply an array with a scalar value rather than 
# another array! It is important to note that two ndarrays can broadcast together only when they are 
# compatible.

# Ndarrays are compatible when:

# Both have the same dimensions
# Either of the ndarrays has a dimension of 1.The one having a dimension of 1 is broadcast to meet the size
# requirements of the larger ndarray

# In case the arrays are not compatible, you will get a ValueError.

a = np.ones((3,3))
b = np.array([2])
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [83]:
# ******************8.NumPy Ufuncs – The secret of its success!***********************
"""Python is a dynamically typed language. This means the data type of a variable does not need to be 
   known at the time of the assignment. Python will automatically determine it at run-time. While this 
   means a cleaner and easier code to write, it also makes Python sluggish.

   This problem manifests itself when Python has to do many operations repeatedly, like the addition of 
   two arrays. This is so because each time an operation needs to be performed, Python has to check the 
   data type of the element. This problem is overcome by NumPy using the ufuncs function.

   The way NumPy makes this work faster is by using vectorization.Vectorization performs the same operation
   on ndarray in an element-by-element fashion in a compiled code. So the data types of the elements do not
   need to be determined every time, thereby performing faster operations.

   ufuncs are Universal functions in NumPy that are simply mathematical functions.They perform fast element
   -wise functions. They are called automatically when you are performing simple arithmetic operations on 
   NumPy arrays because they act as wrappers for NumPy ufuncs.

   For example,when adding two NumPy arrays using ‘+’,the NumPy ufunc add() is automatically called behind
   the scene and quietly does its magic:
"""

a = [1,2,3,4,5]
b = [6,7,8,9,10]
%timeit a+b

150 ns ± 5.48 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [84]:
a = np.arange(1,6)
b = np.arange(6,11)
%timeit a+b

744 ns ± 21.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [85]:
# ***************9.Maths with NumPy arrays*******************
# Basic arithmetic operations on NumPy arrays

# The basic arithmetic operations can easily be performed on NumPy arrays.The important thing to remember 
# is that these simple arithmetics operation symbols just act as wrappers for NumPy ufuncs.

print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [86]:
# Mean, Median and Standard deviation
# To find the mean and standard deviation of a NumPy array, use the mean(), std() and median() methods:

a = np.arange(5,15,2)
print("The array:",a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

The array: [ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [87]:
# Min-Max values and their indexes
# Min and Max values in an ndarray can be easily found using the min() and max() methods:

a = np.array([[1,6],[4,3]])

# print the array
print("The array:",a)
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

The array: [[1 6]
 [4 3]]
Min : [1 3]
Max : [6 4]


In [88]:
# You can also easily determine the index of the minimum or maximum value in the ndarray along a particular
# axis using the argmin() and argmax() methods:

a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


In [89]:
# ******************10.Sorting in NumPy arrays*************************

"""For any programmer,the time complexity of any algorithm is of prime essence.Sorting is an important and
   very basic operation that you might well use on a daily basis as a data scientist. So, it is important 
   to use a good sorting algorithm with minimum time complexity.

   The NumPy library is a legend when it comes to sorting elements of an array. It has a range of sorting 
   functions that you can use to sort your array elements.It has implemented quicksort,heapsort,mergesort,
   and timesort for you under the hood when you use the sort() method:
"""

a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
# You can even sort the array along any axis you desire:

a = np.array([[5,6,7,4],
              [9,2,3,7]])

# sort along the column
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))

# sort along the row
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))

Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]
